logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/server.log
      archivedLogFilenamePattern: ./logs/server-%d.log
      archivedFileCount: 50
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/access.log
        archivedLogFilenamePattern: ./logs/access-%d.log
        archivedFileCount: 50
